services:

  mysql:
    image: mysql:8.4
    container_name: job_processor_mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: job_processor

    ports:
      - "3308:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-prootpassword"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: concurrent_job_processor

    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      SERVER_PORT: 8081

      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: job_processor

    ports:
      - "8081:8081"


volumes:
  mysql_data: